-- insert into recipe (category, description, name, created_at) values ('BREAKFAST', 'lovely PANCIAKI', 'Nalesniki', CURRENT_TIMESTAMP);
-- insert into recipe (category, description, name, created_at) values ('LUNCH', 'lovely Spaghetti', 'Spaghetti', CURRENT_TIMESTAMP);
-- -- insert into recipe (category, description, name, created_at) values ('LUNCH', 'lovely Schabowe', 'Schabowe', CURRENT_TIMESTAMP);
-- insert into recipe (category, description, name, created_at) values ('DINNER', 'lovely Skyr', 'Skyr', CURRENT_TIMESTAMP);
