CREATE TABLE IF NOT EXISTS identity_user (
    id bigint generated by default as identity,
    username varchar(255),
    password varchar(255),
    user_role varchar(255) check (user_role in ('USER','ADMIN')),
    created_at timestamp(6) not null,
    primary key (id)
);