CREATE TABLE IF NOT EXISTS product (
    id bigint generated by default as identity,
    recipe_id bigint,
    name varchar(255),
    measure varchar(255),
    qty float(53),
    created_at timestamp(6) not null,
    primary key (id)
);