spring:
  cloud:
    gateway:
      routes:
        - id: recipes-service
          uri: lb://recipes-service
          predicates:
            - Path=/recipes-service/**
          filters:
            - StripPrefix=1
        - id: test-service
          uri: lb://test-service
          predicates:
            - Path=/test-service/**
          filters:
            - StripPrefix=1
        - id: identity-service
          uri: lb://identity-service
          predicates:
            - Path=/identity-service/**
          filters:
            - StripPrefix=1