spring:
  cloud:
    gateway:
      routes:
        - id: recipes-save
          uri: lb://recipes-service
          predicates:
            - Path=/recipes-service/api/v1/recipes
            - Method=POST
          filters:
            - StripPrefix=1
            - RoleCheck=USER,ADMIN
        - id: recipes-update
          uri: lb://recipes-service
          predicates:
            - Path=/recipes-service/api/v1/recipes
            - Method=PUT
          filters:
            - StripPrefix=1
            - AdminCheck=ADMIN
        - id: recipes-service
          uri: lb://recipes-service
          predicates:
            - Path=/recipes-service/**
          filters:
            - StripPrefix=1
        - id: identity-service
          uri: lb://identity-service
          predicates:
            - Path=/identity-service/**
          filters:
            - StripPrefix=1
#        - id: images-rename
#          uri: lb://images-service
#          predicates:
#            - Path=/images-service/api/v1/images/rename
#          filters:
#            - StripPrefix=1
#            - AdminCheck=ADMIN
        - id: images-service
          uri: lb://images-service
          predicates:
            - Path=/images-service/**
          filters:
            - StripPrefix=1
        - id: products-save
          uri: lb://products-service
          predicates:
            - Path=/products-service/api/v1/products
            - Method=POST
          filters:
            - StripPrefix=1
            - AdminCheck=ADMIN
        - id: products-update
          uri: lb://products-service
          predicates:
            - Path=/products-service/api/v1/products
            - Method=PUT
          filters:
            - StripPrefix=1
            - AdminCheck=ADMIN
        - id: products-service
          uri: lb://products-service
          predicates:
            - Path=/products-service/**
          filters:
            - StripPrefix=1
        - id: votes-update
          uri: lb://votes-service
          predicates:
            - Path=/votes-service/api/v1/votes
            - Method=PUT
          filters:
            - StripPrefix=1
            - AdminCheck=ADMIN
        - id: votes-service
          uri: lb://votes-service
          predicates:
            - Path=/votes-service/**
          filters:
            - StripPrefix=1