spring:
  cloud:
    gateway:
      routes:
        - id: recipes-create
          uri: lb://recipes-service
          predicates:
            - Path=/recipes-service/api/v1/recipes
            - Method=POST
          filters:
            - StripPrefix=1
            - RoleCheck=ADMIN
        - id: recipes-update
          uri: lb://recipes-service
          predicates:
            - Path=/recipes-service/api/v1/recipes
            - Method=PUT
          filters:
            - StripPrefix=1
            - RoleCheck=ADMIN
        - id: recipes-service
          uri: lb://recipes-service
          predicates:
            - Path=/recipes-service/**
          filters:
            - StripPrefix=1
        - id: test-service
          uri: lb://test-service
          predicates:
            - Path=/test-service/**
          filters:
            - StripPrefix=1
        - id: identity-service
          uri: lb://identity-service
          predicates:
            - Path=/identity-service/**
          filters:
            - StripPrefix=1
        - id: images-rename
          uri: lb://images-service
          predicates:
            - Path=/images-service/api/v1/images/rename
          filters:
            - StripPrefix=1
            - RoleCheck=ADMIN
        - id: images-service
          uri: lb://images-service
          predicates:
            - Path=/images-service/**
          filters:
            - StripPrefix=1
        - id: products-service
          uri: lb://products-service
          predicates:
            - Path=/products-service/**
          filters:
            - StripPrefix=1
        - id: votes-service
          uri: lb://votes-service
          predicates:
            - Path=/votes-service/**
          filters:
            - StripPrefix=1