FROM openjdk:8-jre
# moze 11 zadzialaa jak 8 nie zadziala, pamietaj aby zmienic
ADD target/cudanawidelcu-1.0.0.RELEASE.jar app.jar
EXPOSE 1111
EXPOSE 2222
EXPOSE 3333
EXPOSE 4444
# ENTRYPOINT ["java","-jar","/app.jar","accounts"]
